export { schoolFaker } from './school.faker'
export { groupFaker } from './group.faker'
export { employeeFaker } from './employee.faker'
export { titleFaker } from './title.faker'
export { positionFaker } from './position.faker'
export { employeePositionFaker } from './employee-position.faker-r'
