export { SchoolFaker } from './school.faker'
export { GroupFaker } from './group.faker'
export { EmployeeFaker } from './employee.faker'
export { TitleFaker } from './title.faker'
export { PositionFaker } from './position.faker'
export { EmployeePositionFaker, IEmployeePositionFakerD } from './employee-position.faker-r'
export { PromFaker, IPromFakerD } from './prom.faker-r'
