export { ModelFaker } from './model.faker'
export { BorderFaker } from './border.faker'
export { ColorFaker } from './color.faker'
export { SizeFaker } from './size.faker'
export { TypeFaker } from './type.faker'
export { IProductD, ProductFaker } from './product.faker-r'
export { IProfileD, ProfileFaker } from './profile.faker-r'
