export { ModelFaker } from './model.faker'
export { BorderFaker } from './border.faker'
export { ColorFaker } from './color.faker'
export { SizeFaker } from './size.faker'
export { TypeFaker } from './type.faker'
