export { EmployeePosition, IEmployeePosition } from './employee-position.model'
export { Prom, IProm } from './prom.model'
export { Position, IPosition } from './position.model'
export { Employee, IEmployee } from './employee.model'
export { Group, IGroup } from './group.model'
export { Title, ITitle } from './title.model'
export { School, ISchool } from './school.model'
